dist: trusty
sudo: false
language: php

php:
  - 7.2

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

services:
  - redis-server
  - mysql

script:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - vendor/bin/phpunit