dist: trusty
sudo: false
language: php

php:
  - 7.2

services:
  - redis-server
  - mysql

script:
  - composer install
  - php bin/console doctrine:schema:update --force --env=test
  - vendor/bin/phpunit