language: php
sudo: false
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
env:
  global:
    - DATABASE_URL="mysql://root:@127.0.0.1:3306/todolist"
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todolist;'

install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - php bin/console doctrine:schema:update --force

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit ./tests/